//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModelContainer : DbContext
    {
        public ModelContainer()
            : base("name=ModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<QuizInstance> QuizInstances { get; set; }
        public virtual DbSet<QuizQuestionDomain> QuizQuestionDomains { get; set; }
        public virtual DbSet<QuizQuestionInstance> QuizQuestionInstances { get; set; }
        public virtual DbSet<QuizQuestion> QuizQuestions { get; set; }
        public virtual DbSet<QuizQuestionSubdomain> QuizQuestionSubdomains { get; set; }
        public virtual DbSet<Quiz> Quizs { get; set; }
        public virtual DbSet<User_QuizInstance> User_QuizInstance { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
