//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuizQuestionDomain
    {
        public QuizQuestionDomain()
        {
            this.Quizs = new HashSet<Quiz>();
            this.QuizQuestions = new HashSet<QuizQuestion>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Quiz> Quizs { get; set; }
        public virtual ICollection<QuizQuestion> QuizQuestions { get; set; }
    }
}
