//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quiz
    {
        public Quiz()
        {
            this.Quiz_QuizQuestion = new HashSet<Quiz_QuizQuestion>();
        }
    
        public int Id { get; set; }
        public string QuizTitle { get; set; }
        public int Time { get; set; }
        public double PassingScore { get; set; }
        public int Questions { get; set; }
    
        public virtual ICollection<Quiz_QuizQuestion> Quiz_QuizQuestion { get; set; }
    }
}
