//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quiz
    {
        public Quiz()
        {
            this.QuizInstances = new HashSet<QuizInstance>();
        }
    
        public int Id { get; set; }
        public string QuizTitle { get; set; }
        public int Time { get; set; }
        public double PassingScore { get; set; }
        public int NumQuestions { get; set; }
        public int DomainId { get; set; }
    
        public virtual ICollection<QuizInstance> QuizInstances { get; set; }
        public virtual QuizQuestionDomain QuizQuestionDomain { get; set; }
    }
}
