//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuizQuestion
    {
        public QuizQuestion()
        {
            this.Quiz_QuizQuestion = new HashSet<Quiz_QuizQuestion>();
        }
    
        public int Id { get; set; }
        public string QuestionText { get; set; }
        public string Answer1Text { get; set; }
        public bool Answer1Correct { get; set; }
        public string Answer2Text { get; set; }
        public bool Answer2Correct { get; set; }
        public string Answer3Text { get; set; }
        public bool Answer3Correct { get; set; }
    
        public virtual ICollection<Quiz_QuizQuestion> Quiz_QuizQuestion { get; set; }
    }
}
